### PR TITLE
Impl users comments

### LINKED ISSUE #15: Some UI suggestions
- dark mode: dark pink on light black doesn't read well - change the color of dark pink to light pink or so
- page 2
  - why is my previous username not kept?
  - when entering the username and clicking 'create user', it should go on to page 3
  - as the username is not kept in the browser, I cannot enter my old username again. So it should really be kept
- page 3
  - I usually prefer to have the latest transactions on top.
  - And I know you love the `¤`, but to me it looks like the _utf-8 character not found_, so I always wonder what's wrong with my browser
- page 4
  - trying to send 10'000 transactions hangs.
- page 5
  - needs more text: what the demo was about, what is novel (repetition), use-cases, I would even put a link to avalanche

### PR DESCRIPTION
**Pull request by tharvik**
* store user's keys in local storage
* improve dark mode (you can set variable in CSS for material!)
* add much text, either review it direclty or comment on the cryptpad
* use 💶 instead of ¤

### CODE REVIEW

File: web/src/pages/new_account.rs [hunk 1]
```diff
@@ -95,11 +95,16 @@ impl Component for NewAccount {
...
             <h1> { "New account" } </h1>
 
-            <p>
-                { "Here, you can create your own account." }
-                <br />
-                { "You can also see the status of the network below." }
-            </p>
+            <p> { "
+                Here, you can create your own account.
+                It will automatically be credited with a certain amount of
```
Comment (ineiti) [inline web/src/pages/new_account.rs]:
```suggestion
                It will automatically be credited with a fixed amount of
```

File: web/src/pages/new_account.rs [hunk 2]
```diff
@@ -95,11 +95,16 @@ impl Component for NewAccount {
...
+                asset that you can pass around.
+                This account will be stored in your browser, so if you
```
Comment (ineiti) [inline web/src/pages/new_account.rs]:
```suggestion
                This account is stored in your browser, so if you
```

File: web/src/pages/speedtest.rs [hunk 3]
```diff
@@ -241,16 +241,19 @@ impl Component for Speedtest {
...
+                for many more transactions per second (TPS) than currently
+                existing blockchains.
+                Here you can actually test it, flooding the servers with
+                transactions.
+            " } <br /> { "
+                Bear in mind that the transactions are sent by your browser to
+                a node, which then forwards them on the actual network.
+                This greatly reduces the computed TPS as opposed to sending
+                your transactions using your node directly as you would do in
+                a more realistic use case.
```
Comment (ineiti) [inline web/src/pages/speedtest.rs]: ... and means that the TPS measured here is below the speed reported in the paper.

File: web/src/pages/summary.rs [hunk 4]
```diff
@@ -22,21 +22,52 @@ impl Component for Summary {
...
-            <p> { "We showed that AT2 is faster than other well known
-                   blockchains. It achieves that speed by avoiding to
-                   sync a common state, the global consensus. Most
-                   blockchains are still using this method, but AT2's
-                   paper demonstrates that it is unneeded to transfer
-                   assets inside a network."
-            } </p>
+            <p> { "
+                We showed that AT2 is behaving as any other blockchain.
+                You can send asset with it, see other users on the network
```
Comment (ineiti) [inline web/src/pages/summary.rs]:
```suggestion
                You can send assets with it, see other users on the network
```

File: web/src/pages/summary.rs [hunk 5]
```diff
@@ -22,21 +22,52 @@ impl Component for Summary {
...
+                and the latest processed transactions.
+                But using a speedtest really uncovered the true power of AT2:
+                it is faster than other well known blockchains, beating Bitcoin
+                and Etherium by a ~10x factor.
```
Comment (ineiti) [inline web/src/pages/summary.rs]:
```suggestion
                and Etherium by a factor of 10.
```

File: web/src/pages/summary.rs [hunk 6]
```diff
@@ -22,21 +22,52 @@ impl Component for Summary {
...
+                It achieves that speed by avoiding to sync a common state,
+                the global consensus, but uses a local one, allowing nodes
+                to validate transactions before checking theses with every other
```
Comment (ineiti) [inline web/src/pages/summary.rs]:
```suggestion
                to validate transactions before checking them with every other
```

File: web/src/pages/summary.rs [hunk 7]
```diff
@@ -22,21 +22,52 @@ impl Component for Summary {
...
+                node on the network.
+            " } </p>
+
+            <p> { "
+                As the transaction time is so short and that it can run in a
```
Comment (ineiti) [inline web/src/pages/summary.rs]:
```suggestion
                As the transaction time is so short and because it can run in a
```

File: web/src/pages/summary.rs [hunk 8]
```diff
@@ -22,21 +22,52 @@ impl Component for Summary {
...
+                browser, one can imagine using it directly as a mean of
```
Comment (ineiti) [inline web/src/pages/summary.rs]:
```suggestion
                browser, one can imagine using it directly as a means of
```

File: web/src/pages/summary.rs [hunk 9]
```diff
@@ -22,21 +22,52 @@ impl Component for Summary {
...
+                payment, having a little \"pay with AT2\" next to the credit
```
Comment (ineiti) [inline web/src/pages/summary.rs]:
```suggestion
                payment, having a little button \"pay with AT2\" next to the credit
```

File: web/src/pages/summary.rs [hunk 10]
```diff
@@ -22,21 +22,52 @@ impl Component for Summary {
...
+                cards.
+                Or you can use directly AT2 as a mean of communication, an
```
Comment (ineiti) [inline web/src/pages/summary.rs]:
```suggestion
                Or you can use directly AT2 as a means of communication, an
```

File: web/src/pages/summary.rs [hunk 11]
```diff
@@ -22,21 +22,52 @@ impl Component for Summary {
...
+                instant chat ensuring that no rogue participant can interfere
+                or reorder the messages.
+            " } </p>
 
-            <p> { "If you are interested in exploring this project more,
-                   look at " }
+            <p> { "
+                Most blockchains are still using this global consensus method,
```
Comment (ineiti) [inline web/src/pages/summary.rs]:
```suggestion
                Most blockchains are still using the global consensus method,
```

File: web/src/pages/welcome.rs [hunk 12]
```diff
@@ -23,21 +23,31 @@ impl Component for Welcome {
...
             <p> { "
-                AT2 means Asynchronous Trustworthy Transfer, it is a new way
-                to transfer assets (such as coins) throughout a network of
-                potentially rogues participants.
+                AT2 stands for Asynchronous Trustworthy Transfer, it is a
+                new way to transfer assets (such as coins) throughout a
+                network of potentially rogue participants.
                 It is quite close to Bitcoin in its capabilities, while
-                being order of magnitudes faster and consuming way less
+                being order of magnitudes faster and consuming much less
```
Comment (ineiti) [inline web/src/pages/welcome.rs]:
```suggestion
                being orders of magnitudes faster and consuming much less
```

File: web/src/pages/welcome.rs [hunk 13]
```diff
@@ -23,21 +23,31 @@ impl Component for Welcome {
...
                 energy.
+                It achieves such speed by avoiding to sync a common state,
```
Comment (ineiti) [inline web/src/pages/welcome.rs]:
```suggestion
                It achieves such speed by avoiding to synchronize a common state,
```

File: web/src/pages/welcome.rs [hunk 14]
```diff
@@ -23,21 +23,31 @@ impl Component for Welcome {
...
+                the global consensus, in favor of using a local consensus,
+                that usually isn't the same at every node but does converge
+                to a common state.
+                This way, transactions can be processed as soon as these are
+                happening, not when the whole network agrees on what is the
+                correct ordering.
```
Comment (ineiti) [inline web/src/pages/welcome.rs]:
```suggestion
                happening, not when the whole network agrees on what the
                correct ordering is.
```

File: web/src/pages/welcome.rs [hunk 15]
```diff
@@ -23,21 +23,31 @@ impl Component for Welcome {
...
-                In this demonstrator, you will first create an account
-                that will be credited with some initial asset.
-                You will then use it to send money to some other account on
-                the network, as you would do in a classic blockchain.
-                To show that indeed AT2 is blazing fast, the last part is
-                a speed test where you will send as many transaction as you
+                This demonstrator will take you through a classic identity
+                creation as you would do on another blockchain, but there
+                is a twist at the end.
+                First, you will first create an account that will be credited
```
Comment (ineiti) [inline web/src/pages/welcome.rs]:
```suggestion
                First, you will create an account that will be credited
```

File: web/src/pages/welcome.rs [hunk 16]
```diff
@@ -23,21 +23,31 @@ impl Component for Welcome {
...
+                with some initial assets. You will then use it to send money
```
Comment (ineiti) [inline web/src/pages/welcome.rs]:
```suggestion
                with some initial assets. You can then use it to send money
```

File: web/src/pages/welcome.rs [hunk 17]
```diff
@@ -23,21 +23,31 @@ impl Component for Welcome {
...
+                to another identity on the network, as you would do on other
+                distributed ledger.
+                To show that indeed AT2 is blazing fast, the last part is a
```
Comment (ineiti) [inline web/src/pages/welcome.rs]:
```suggestion
                To show that indeed AT2 is blazingly fast, the last part is a
```

File: web/src/pages/welcome.rs [hunk 18]
```diff
@@ -23,21 +23,31 @@ impl Component for Welcome {
...
+                speed test where you will send as many transactions as you
```
Comment (ineiti) [inline web/src/pages/welcome.rs]:
```suggestion
                speed test where you can send as many transactions as you
```

**Review by ineiti — CHANGES_REQUESTED** [review]

File: web/src/pages/summary.rs (hunk 10 above)
Comment (tharvik) [reply web/src/pages/summary.rs]: so weird, it still takes a "s" even when singular..

**Comment by tharvik** [comment]
@ineiti thanks for the big text review :)

**Review by ineiti — APPROVED** [review]
